import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated from the folders under docs/. Category label and order live in each
// folder's _category_.json; page order is `sidebar_position` in front matter.
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
